In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
PREFIX = "./"

# Input
SAMPLE_DATASET_PATH = PREFIX + "sample_submission.csv"
TRAIN_DATASET_PATH = PREFIX + "train.csv"
TEST_DATASET_PATH = PREFIX + "test.csv"

# Output
RESULT = "TEMER_result.csv"

In [4]:
train_data = pd.read_csv(TRAIN_DATASET_PATH, sep=",")
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   10000 non-null  int64  
 1   age                  10000 non-null  float64
 2   years_of_experience  10000 non-null  float64
 3   lesson_price         10000 non-null  float64
 4   qualification        10000 non-null  float64
 5   physics              10000 non-null  float64
 6   chemistry            10000 non-null  float64
 7   biology              10000 non-null  float64
 8   english              10000 non-null  float64
 9   geography            10000 non-null  float64
 10  history              10000 non-null  float64
 11  mean_exam_points     10000 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 937.6 KB


In [5]:
X_df = train_data.drop(['Id', 'mean_exam_points'], axis = 1)
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  10000 non-null  float64
 1   years_of_experience  10000 non-null  float64
 2   lesson_price         10000 non-null  float64
 3   qualification        10000 non-null  float64
 4   physics              10000 non-null  float64
 5   chemistry            10000 non-null  float64
 6   biology              10000 non-null  float64
 7   english              10000 non-null  float64
 8   geography            10000 non-null  float64
 9   history              10000 non-null  float64
dtypes: float64(10)
memory usage: 781.4 KB


In [6]:
X_train = X_df.values
X_train

array([[4.00e+01, 0.00e+00, 1.40e+03, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [4.80e+01, 4.00e+00, 2.85e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.90e+01, 0.00e+00, 1.20e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       ...,
       [3.40e+01, 1.00e+00, 1.25e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.30e+01, 3.00e+00, 1.10e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [3.50e+01, 0.00e+00, 1.45e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00]])

In [7]:
y_df = train_data[['mean_exam_points']]
y_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   mean_exam_points  10000 non-null  float64
dtypes: float64(1)
memory usage: 78.2 KB


In [8]:
y_train = y_df.values.flatten()
y_train

array([63., 86., 53., ..., 58., 51., 59.])

In [9]:
test_data = pd.read_csv(TEST_DATASET_PATH, sep=",")
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   10000 non-null  int64  
 1   age                  10000 non-null  float64
 2   years_of_experience  10000 non-null  float64
 3   lesson_price         10000 non-null  float64
 4   qualification        10000 non-null  float64
 5   physics              10000 non-null  float64
 6   chemistry            10000 non-null  float64
 7   biology              10000 non-null  float64
 8   english              10000 non-null  float64
 9   geography            10000 non-null  float64
 10  history              10000 non-null  float64
dtypes: float64(10), int64(1)
memory usage: 859.5 KB


In [10]:
x_df = test_data.drop(['Id'], axis = 1)
x_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  10000 non-null  float64
 1   years_of_experience  10000 non-null  float64
 2   lesson_price         10000 non-null  float64
 3   qualification        10000 non-null  float64
 4   physics              10000 non-null  float64
 5   chemistry            10000 non-null  float64
 6   biology              10000 non-null  float64
 7   english              10000 non-null  float64
 8   geography            10000 non-null  float64
 9   history              10000 non-null  float64
dtypes: float64(10)
memory usage: 781.4 KB


In [11]:
X_test = x_df.values
X_test

array([[4.60e+01, 3.00e+00, 1.05e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [4.30e+01, 3.00e+00, 1.85e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [5.20e+01, 1.00e+00, 1.55e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       ...,
       [3.30e+01, 5.00e+00, 1.10e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [4.80e+01, 0.00e+00, 1.75e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [4.90e+01, 5.00e+00, 2.00e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00]])

---

In [12]:
def gb_predict(X, trees_list, coef_list, eta):
    """предсказание с помощью градиентного бустинга"""
    # Реализуемый алгоритм градиентного бустинга будет инициализироваться нулевыми значениями,
    # поэтому все деревья из списка trees_list уже являются дополнительными и при предсказании 
    # прибавляются с шагом eta
    return np.array([sum([
        eta * coef * alg.predict([x])[0] for alg, coef in zip(trees_list, coef_list)]) 
                     for x in X])

In [13]:
def mean_squared_error(y_real, prediction):
    """среднеквадратичная ошибка"""
    return (sum((y_real - prediction) ** 2)) / len(y_real)

In [14]:
def bias(y, z):
    """смещение для L2-loss"""
    return - 2 * (z - y)

In [15]:
def gb_fit(DecisionTreeClass, n_trees, max_depth, X, y, coefs, eta):
    """обучение градиентного бустинга"""
    
    # eta - скорость обучения
    # Деревья будем записывать в список
    trees = []
    
    # Будем записывать ошибки
    errors = []
    
    for i in range(n_trees):
        tree = DecisionTreeClass(max_depth=max_depth, random_state=42)

        # инициализируем бустинг начальным алгоритмом, возвращающим ноль, 
        # поэтому первый алгоритм просто обучаем на выборке и добавляем в список
        if len(trees) == 0:
            # обучаем первое дерево на обучающей выборке
            tree.fit(X, y)
            
            errors.append(mean_squared_error(y, gb_predict(X, trees, coefs, eta)))
        else:
            # Получим ответы на текущей композиции
            target = gb_predict(X, trees, coefs, eta)
            
            # алгоритмы, начиная со второго, обучаем на сдвиг
            tree.fit(X, bias(y, target))
            
            errors.append(mean_squared_error(y, gb_predict(X, trees, coefs, eta)))

        trees.append(tree)
        
    return trees, errors

In [16]:
def evaluate_alg(X_train, X_test, y_train, y_test, trees, coefs, eta):
    """ошибка алгоритма на тренировочной и тестовой выборках"""
    
    train_prediction = gb_predict(X_train, trees, coefs, eta)

    print(f'Ошибка алгоритма из\t{n_trees} деревьев\tглубиной {max_depth}'
          f'\tс шагом {eta}\tна тренировочной выборке:\t{round(mean_squared_error(y_train, train_prediction))}')

    test_prediction = gb_predict(X_test, trees, coefs, eta)

    print(f'Ошибка алгоритма из\t{n_trees} деревьев\tглубиной {max_depth}'
          f'\tс шагом {eta}\tна   тестовой    выборке:\t{round(mean_squared_error(y_test, test_prediction))}')

In [17]:
def gini(labels):
    """критерий Джини"""
    #  подсчёт количества объектов разных классов
    classes = {}
    for label in labels:
        if label not in classes:
            classes[label] = 0
        classes[label] += 1
    
    #  расчёт критерия
    impurity = 1 # коэффициент неопределённости Джини
    for label in classes:
        p = classes[label] / len(labels)
        impurity -= p ** 2
    return impurity

In [18]:
class Node:
    """узел дерева"""
    
    def __init__(self, index, t, true_branch, false_branch):
        self.index = index  # индекс признака, по которому ведётся сравнение с порогом в этом узле
        self.t = t  # значение порога
        self.true_branch = true_branch  # поддерево, удовлетворяющее условию в узле
        self.false_branch = false_branch  # поддерево, не удовлетворяющее условию в узле

In [19]:
class Leaf:
    """лист дерева"""
    
    def __init__(self, data, labels, regression):
        self.data = data
        self.labels = labels
        self.regression = regression
        self.prediction = self.predict()
        
    def predict(self):
        if self.regression:
            prediction = np.mean(self.labels)  # среднее значение по выборке
        else:
            # подсчёт количества объектов разных классов
            classes = {}  # сформируем словарь "класс: количество объектов"
            for label in self.labels:
                if label not in classes:
                    classes[label] = 0 
                classes[label] += 1
            # найдём класс, количество объектов которого будет максимальным в этом листе и вернём его
            prediction = max(classes, key=classes.get)
        return prediction

In [20]:
class MyDecisionTree:
    def __init__(self, random_state=None, min_leaf=1, max_depth=10**9, max_leaf_nodes=10**9, regression=True):
        """
        конструктор дерева

        :param min_leaf: минимальное количество объектов в листе
        :param max_depth: максимальная глубина дерева
        :param max_leaf_nodes: максимальное количество листьев
        :param inf_crit_func: критерий информативности
        """
        self.root = None
        self.min_leaf = min_leaf
        self.max_depth = max_depth
        self.max_leaf_nodes = max_leaf_nodes
        self.regression = regression
        self.inf_crit_func = np.var if regression else gini  # критерий информативности
    
    def quality(self, left_labels, right_labels, current_inf_crit):
        """расчёт качества"""
        # доля выбоки, ушедшая в левое поддерево
        p = float(left_labels.shape[0]) / (left_labels.shape[0] + right_labels.shape[0])  
        return current_inf_crit - p * self.inf_crit_func(left_labels) - (1 - p) * self.inf_crit_func(right_labels)
    
    def split(self, data, labels, index, t):
        """разбиение датасета в узле"""

        left = np.where(data[:, index] <= t)
        right = np.where(data[:, index] > t)

        true_data = data[left]
        false_data = data[right]
        true_labels = labels[left]
        false_labels = labels[right]

        return true_data, false_data, true_labels, false_labels
    
    def find_best_split(self, data, labels):
        """нахождение наилучшего разбиения"""

        current_inf_crit = self.inf_crit_func(labels)

        best_quality = 0
        best_t = None
        best_index = None

        n_features = data.shape[1]

        for index in range(n_features):
            # будем проверять только уникальные значения признака, исключая повторения
            t_values = np.unique([row[index] for row in data])

            for t in t_values:
                true_data, false_data, true_labels, false_labels = self.split(data, labels, index, t)
                # пропускаем разбиения, в которых в узле остаётся менее min_leaf объектов
                if len(true_data) < self.min_leaf or len(false_data) < self.min_leaf:
                    continue

                current_quality = self.quality(true_labels, false_labels, current_inf_crit)

                # выбираем порог, на котором получается максимальный прирост качества
                if current_quality > best_quality:
                    best_quality, best_t, best_index = current_quality, t, index

        return best_quality, best_t, best_index
    
    def build_tree(self, data, labels, _leaves=0, _branches=0, _depth=0):
        """
        построение дерева с помощью рекурсивной функции

        :param data: данные
        :param labels: метки
        :return: узел дерева, кол-во листьев, кол-во ветвей
        """

        quality, t, index = self.find_best_split(data, labels)

        # Базовый случай - прекращаем рекурсию, когда нет прироста в качества
        if (quality == 0) or ((self.max_leaf_nodes - _leaves - _branches) < 2) or (_depth >= self.max_depth):
            _leaves += 1
            return Leaf(data, labels, regression=self.regression), _leaves, _branches

        true_data, false_data, true_labels, false_labels = self.split(data, labels, index, t)

        # Рекурсивно строим два поддерева
        _branches += 1
        true_branch, _leaves, _branches = self.build_tree(true_data, true_labels, _leaves, _branches, _depth+1)
        _branches -= 1
        false_branch, _leaves, _branches = self.build_tree(false_data, false_labels, _leaves, _branches, _depth+1)

        # Возвращаем класс узла со всеми поддеревьями, то есть целого дерева
        self.root = Node(index, t, true_branch, false_branch)
        return self.root, _leaves, _branches
    
    def classify_object(self, obj, node):
        #  Останавливаем рекурсию, если достигли листа
        if isinstance(node, Leaf):
            answer = node.prediction
            return answer

        if obj[node.index] <= node.t:
            return self.classify_object(obj, node.true_branch)
        else:
            return self.classify_object(obj, node.false_branch)
        
    def fit(self, X, y):
        reg_tree, *_ = self.build_tree(X, y)
        return reg_tree
    
    def predict(self, X):
        classes = []
        for obj in X:
            prediction = self.classify_object(obj, self.root)
            classes.append(prediction)
        return classes

In [21]:
n_trees = 50
coefs = [1] * n_trees  # для простоты примем коэффициенты равными 1
max_depth = 5
eta = 0.1

trees, errors = gb_fit(MyDecisionTree, n_trees, max_depth, X_train, y_train, coefs, eta)

In [22]:
prediction = gb_predict(X_test, trees, coefs, eta)
prediction

array([54.55889478, 63.19890738, 48.33675996, ..., 53.64758869,
       64.39666779, 69.70579774])

In [23]:
res = test_data[['Id']].copy()
res = pd.concat([res, pd.DataFrame(prediction, columns=['mean_exam_points'])], axis=1)
res

Id  mean_exam_points
0     10000         54.558895
1     10001         63.198907
2     10002         48.336760
3     10003         91.098666
4     10004         89.397810
...     ...               ...
9995  19995         42.690808
9996  19996         79.036002
9997  19997         53.647589
9998  19998         64.396668
9999  19999         69.705798

[10000 rows x 2 columns]

In [24]:
res.to_csv(RESULT, sep=",", index=False)